### ISSUE TITLE
Schematics and other details are missing

### ISSUE THREAD

**Issue by tommythorn** [RISCV-on-Microsemi-FPGA/Documentation#3]
It's a bit frustrating to read 
"For more information, to get schematics, software, guides etc., please register and download:
http://www.FutureElectronics.com/CreativeDevelopmentBoard" on http://www1.futureelectronics.com/Mailing/etechs/Microsemi/etechALERT_Microsemi_CreativeBoard/MicrosemiCreativeQuickStart.pdf when that link leads nowhere.  The only example designs are not only very large but they don't (AFAICT) include the full IO constraints.

I hit a brick wall trying to bring this up with either Future Electronics or Microsemi, but this repo is where you'd expect to find such info, so as a last ditch effort, I'll try here.

**Comment by kevinscully100** [comment]
To clarify, did you register on the Future site? Does the link function after registration?

**Comment by CLappin** [comment]
Hi Tommy and Kevin,

I've taken a look at the future site, being registered and not and the links are dead. 
Tommy, I believe  I have a copy of schematics available on my HDD and I will upload them and any other documentation I can find to this documents page in the next day or so. 
If not please send a reminder.
Thank you for bring this to our attention. 
Ciaran

**Comment by CLappin** [comment]
Hi Tommy,

Please find the User Guide for the Creative Board in the link below.
[User Guide](https://github.com/RISCV-on-Microsemi-FPGA/Documentation/blob/master/Future%20Electronics%20Microsemi%20Creative%20Development%20Board%20User%20Guide%20Rev%201.pdf)

Thanks
Ciaran
